/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UseCase = IDL.Variant({
  'Banking' : IDL.Null,
  'Content' : IDL.Null,
  'Gambling' : IDL.Null,
});
export const Submission = IDL.Record({
  'useCase' : UseCase,
  'phoneNumber' : IDL.Text,
});
export const VerificationResult = IDL.Record({
  'verified' : IDL.Bool,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'getSubmissionsByUseCase' : IDL.Func(
      [UseCase],
      [IDL.Vec(Submission)],
      ['query'],
    ),
  'getVerificationCount' : IDL.Func([UseCase], [IDL.Nat], ['query']),
  'submitPhoneNumber' : IDL.Func([IDL.Text, UseCase], [VerificationResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UseCase = IDL.Variant({
    'Banking' : IDL.Null,
    'Content' : IDL.Null,
    'Gambling' : IDL.Null,
  });
  const Submission = IDL.Record({
    'useCase' : UseCase,
    'phoneNumber' : IDL.Text,
  });
  const VerificationResult = IDL.Record({
    'verified' : IDL.Bool,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'getSubmissionsByUseCase' : IDL.Func(
        [UseCase],
        [IDL.Vec(Submission)],
        ['query'],
      ),
    'getVerificationCount' : IDL.Func([UseCase], [IDL.Nat], ['query']),
    'submitPhoneNumber' : IDL.Func(
        [IDL.Text, UseCase],
        [VerificationResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };